name: packer

on:
  push:

env:
  PRODUCT_VERSION: "1.10.2" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./base.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./base.pkr.hcl"
