name: packer

on:
  push:

env:
  PRODUCT_VERSION: "1.10.2" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        env:
          IBM_API_KEY: ${{ secrets.ibm_api_key }}
          SUBNET_ID: ${{ vars.subnet_id }}
          REGION: ${{ vars.region }}
          RESOURCE_GROUP_NAME: ${{ vars.resource_group_name }}
        run: |
          echo "IBM_API_KEY=$IBM_API_KEY" >> $GITHUB_ENV
          echo "SUBNET_ID=$SUBNET_ID" >> $GITHUB_ENV
          echo "REGION=$REGION" >> $GITHUB_ENV
          echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV


      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./base.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./base.pkr.hcl"
